use_frameworks!

platform :ios, '11.0'

target 'TSWebView_Example' do
  pod 'TSWebView', :path => '../'

  target 'TSWebView_Tests' do
    inherit! :search_paths

#    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
